<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * P4-74 — changer son adresse e-mail avec confirmation d'abord, bascule ensuite.
 *
 * L'adresse courante reste active tant que la nouvelle n'est pas confirmée :
 * `app_user.pending_email` porte l'adresse EN ATTENTE (nullable, unique — deux
 * comptes ne peuvent pas réserver la même), et `email_change_token` est le
 * jeton de confirmation à usage unique (même recette que
 * email_verification_token : hash sha256, TTL, single-use), envoyé À la nouvelle
 * adresse. Table globale (référence User, pas de club_id) → pas de RLS, un simple
 * grant du rôle runtime, comme email_verification_token / reset_password_request.
 */
final class Version20260810160000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'P4-74: app_user.pending_email + email_change_token store (confirm-then-switch email change).';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE app_user ADD pending_email VARCHAR(180) DEFAULT NULL');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_pending_email ON app_user (pending_email)');

        $this->addSql('CREATE TABLE email_change_token (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id UUID NOT NULL, hashed_token VARCHAR(64) NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_email_change_hashed_token ON email_change_token (hashed_token)');
        $this->addSql('CREATE INDEX idx_email_change_user ON email_change_token (user_id)');
        $this->addSql('ALTER TABLE email_change_token ADD CONSTRAINT fk_email_change_user FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE');

        // Global table (no club_id → no RLS), only a runtime-role grant, like
        // email_verification_token. The identity sequence is advanced by the
        // table INSERT, so no separate grant.
        $appRole = $this->connection->fetchOne('SELECT rolname FROM pg_roles WHERE rolname IN (\'app_user\', \'amateo_app\') ORDER BY (rolname = \'amateo_app\') DESC LIMIT 1');
        if (\is_string($appRole)) {
            $this->addSql('GRANT SELECT, INSERT, UPDATE, DELETE ON email_change_token TO ' . $appRole);
        }
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE email_change_token DROP CONSTRAINT fk_email_change_user');
        $this->addSql('DROP TABLE email_change_token');
        $this->addSql('DROP INDEX uniq_user_pending_email');
        $this->addSql('ALTER TABLE app_user DROP pending_email');
    }
}
