<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * A3 (anti-enumeration): email-verified registration. Adds the single-use
 * email_verification_token store (carries the deferred club-creation intent) and
 * backfills every existing account as verified so the new login gate does not lock
 * out the current user base. The table is global (no club_id) → no RLS policy, only
 * a runtime-role grant, like reset_password_request.
 */
final class Version20260709130000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'A3: email_verification_token store + backfill existing users as verified.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE email_verification_token (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id UUID NOT NULL, hashed_token VARCHAR(64) NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ara VARCHAR(20) NOT NULL, club_name VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_email_verification_hashed_token ON email_verification_token (hashed_token)');
        $this->addSql('CREATE INDEX idx_email_verification_user ON email_verification_token (user_id)');
        $this->addSql('ALTER TABLE email_verification_token ADD CONSTRAINT fk_email_verification_user FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE');

        // Runtime role needs DML on the new global table (no RLS: no club_id). The
        // identity sequence is advanced by the table INSERT, so no separate grant.
        $appRole = $this->connection->fetchOne('SELECT rolname FROM pg_roles WHERE rolname IN (\'app_user\', \'amateo_app\') ORDER BY (rolname = \'amateo_app\') DESC LIMIT 1');
        if (\is_string($appRole)) {
            $this->addSql('GRANT SELECT, INSERT, UPDATE, DELETE ON email_verification_token TO ' . $appRole);
        }

        // Backfill: treat every pre-existing account as verified, else the login gate
        // (emailVerifiedAt IS NULL → rejected) would lock out the entire current user
        // base and all fixtures. created_at (timestamptz) casts to the timestamp column;
        // the exact instant is irrelevant — any non-null value means "verified".
        $this->addSql('UPDATE app_user SET email_verified_at = created_at::timestamp(0) WHERE email_verified_at IS NULL');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE email_verification_token DROP CONSTRAINT fk_email_verification_user');
        $this->addSql('DROP TABLE email_verification_token');
        // The backfill is not cleanly reversible (the prior NULLs are unrecoverable).
    }
}
